#!/bin/bash

# @copyright Copyright (c) 2017 Arthur Schiwon <blizzz@arthur-schiwon.de>
#
# @author Arthur Schiwon <blizzz@arthur-schiwon.de>
#
# @license GNU AGPL version 3 or any later version
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -e "/var/www/html/config/config.php" ]; then
    cp -Ra "/var/www/html/config" "$NC_PERMCONFDIR/"
fi

# changed with the upgrade from Nextcloud 13 to 14.0.4
# TODO: remove this block once Nc 14 is end of life
if [ -e "$NC_PERMCONFDIR_OLD/config/config.php" ]; then
    rm "$NC_PERMCONFDIR_OLD/config/config.php"
fi
